package ak.dev.khi_archive_platform.platform.model.physicalmedia;

import ak.dev.khi_archive_platform.platform.enums.DigitizationStatus;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.persistence.Version;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.Instant;
import java.time.LocalDate;

/**
 * Inventory row for one physical artefact (cassette, reel, DVD, …) prepared
 * by the archive team.
 *
 * <p>All 29 columns of the source spreadsheet ({@code All Final Archive
 * Lists.xlsx → Sheet1}) are mapped 1:1 onto fields here, so the importer can
 * round-trip the sheet without losing context. Two columns are encoded:
 * <ul>
 *   <li>{@code digitization} — Excel 0/1/2 → {@link DigitizationStatus}.</li>
 *   <li>{@code needToClear} — Excel 0/1 → boolean.</li>
 * </ul>
 *
 * <p>The internal {@code pmCode} ({@code PM_NNNNNN}) is our unique business
 * key so a row can be referenced even when the user-supplied
 * {@code physicalLabel} from the sheet repeats across media types.
 *
 * <p>Soft-delete is the same pattern as audio: setting {@code removedAt}
 * trashes the row; admins can restore or purge from the trash listing.
 */
@Entity
@Table(name = "physical_media",
        uniqueConstraints = {
                @UniqueConstraint(name = "uk_pm_code", columnNames = "pm_code")
        },
        indexes = {
                @Index(name = "idx_pm_code", columnList = "pm_code"),
                @Index(name = "idx_pm_physical_label", columnList = "physical_label"),
                @Index(name = "idx_pm_media_type", columnList = "physical_media_type"),
                @Index(name = "idx_pm_media_category", columnList = "media_category"),
                @Index(name = "idx_pm_digitization", columnList = "digitization"),
                @Index(name = "idx_pm_need_to_clear", columnList = "need_to_clear"),
                @Index(name = "idx_pm_removed_at", columnList = "removed_at")
        })
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PhysicalMedia {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Internal unique business key (e.g. {@code PM_000001}). Generated by
     *  the service; immutable once assigned. */
    @Column(name = "pm_code", nullable = false, length = 60, unique = true)
    private String pmCode;

    // ─── Source-sheet columns (29) ───────────────────────────────────────────

    /** {@code No.} — row ordinal as recorded in the sheet. */
    @Column(name = "row_number")
    private Integer rowNumber;

    /** {@code Number} — <b>per-media-type contiguous counter</b>. Every
     *  physical media type carries its own 1..N sequence (Audio Cassette
     *  1..1893, VHS Cassette 1..55, …). When the importer round-trips the
     *  sheet the original value is preserved; on a manual create the service
     *  <b>always</b> mints {@code max(Number)+1} for that media type and
     *  ignores any client-supplied value. */
    @Column(name = "inventory_number")
    private Integer inventoryNumber;

    /** {@code Physical Media Type} — e.g. {@code Audio Cassette}, {@code VHS}. */
    @Column(name = "physical_media_type", length = 200)
    private String physicalMediaType;

    /** {@code Media Category} — high-level bucket: Audio, Video, … */
    @Column(name = "media_category", length = 200)
    private String mediaCategory;

    /** {@code Title} — display title in Sorani Kurdish/free-text. */
    @Column(name = "title", columnDefinition = "TEXT")
    private String title;

    /** {@code Size GB} — digital file size in gigabytes, stored as free text
     *  (e.g. {@code 4.7}, {@code 4.7 GB}, {@code 700 MB}). Repurposed from the
     *  retired {@code sub_type} column; distinct from {@link #physicalSize}. */
    @Column(name = "size_gb", length = 200)
    private String sizeGB;

    /** {@code Physical Label} — physical sticker/label on the artefact.
     *  Not globally unique — only meaningful within a media type. */
    @Column(name = "physical_label", length = 200)
    private String physicalLabel;

    /** {@code Physical Size} — material size of the artefact
     *  (e.g. big / medium / normal / small). Distinct from {@link #sizeGB},
     *  the digital file size. Backed by the {@code physical_size} column,
     *  migrated once from the legacy {@code size} column. */
    @Column(name = "physical_size", length = 200)
    private String physicalSize;

    /** {@code Content} — free-text content description. */
    @Column(name = "content", columnDefinition = "TEXT")
    private String content;

    /** {@code Archive Dep Note} — archive department note. */
    @Column(name = "archive_dep_note", columnDefinition = "TEXT")
    private String archiveDepNote;

    /** {@code Digitization} — 0=NOT_DIGITIZED, 1=DIGITIZED, 2=DUPLICATED. */
    @Enumerated(EnumType.STRING)
    @Column(name = "digitization", length = 20)
    private DigitizationStatus digitization;

    /** {@code Owner} — owner / producer attribution. */
    @Column(name = "owner", columnDefinition = "TEXT")
    private String owner;

    /** {@code Year} — year on the artefact label. */
    @Column(name = "year")
    private Integer year;

    /** {@code Duration Min} — runtime in minutes. */
    @Column(name = "duration_min")
    private Integer durationMin;

    /** {@code Track Numbers} — count of tracks. */
    @Column(name = "track_numbers")
    private Integer trackNumbers;

    /** {@code Track Name} — free-text track listing. */
    @Column(name = "track_name", columnDefinition = "TEXT")
    private String trackName;

    /** {@code Extension} — file extension produced on capture (e.g. wav, mp4). */
    @Column(name = "extension", length = 50)
    private String extension;

    /** {@code Bit Depth / Color Depth}. */
    @Column(name = "bit_or_color_depth", length = 100)
    private String bitOrColorDepth;

    /** {@code Sample Rate kHz / Frame Rate fps}. */
    @Column(name = "sample_or_frame_rate", length = 100)
    private String sampleOrFrameRate;

    /** {@code Channels / Resolution}. */
    @Column(name = "channels_or_resolution", length = 100)
    private String channelsOrResolution;

    /** {@code Playback Model} — playback hardware used during capture. */
    @Column(name = "playback_model", columnDefinition = "TEXT")
    private String playbackModel;

    /** {@code Capture Interface} — audio/video interface in front of the playback. */
    @Column(name = "capture_interface", columnDefinition = "TEXT")
    private String captureInterface;

    /** {@code Signal Interface (Cable Type)}. */
    @Column(name = "signal_interface", columnDefinition = "TEXT")
    private String signalInterface;

    /** {@code Ingest Software} — application used during ingest. */
    @Column(name = "ingest_software", columnDefinition = "TEXT")
    private String ingestSoftware;

    /** {@code Format / Codec}. */
    @Column(name = "format_codec", length = 200)
    private String formatCodec;

    /** {@code Digitize Date}. Stored as a calendar
     *  date because the sheet only carries day-precision and the importer
     *  must not invent a time-zone. */
    @Column(name = "digitize_date")
    private LocalDate digitizeDate;

    /** {@code Tags} — free-text tag list (comma/slash-separated as found). */
    @Column(name = "tags", columnDefinition = "TEXT")
    private String tags;

    /** {@code Need to Clear} — 0/1 in Excel, stored as a boolean. */
    @Column(name = "need_to_clear")
    private Boolean needToClear;

    /** {@code Capture Dep Note} — capture department note. */
    @Column(name = "capture_dep_note", columnDefinition = "TEXT")
    private String captureDepNote;

    // ─── Audit / soft-delete ─────────────────────────────────────────────────

    @Column(name = "created_at")
    private Instant createdAt;

    @Column(name = "updated_at")
    private Instant updatedAt;

    @Column(name = "removed_at")
    private Instant removedAt;

    @Column(name = "created_by", length = 120)
    private String createdBy;

    @Column(name = "updated_by", length = 120)
    private String updatedBy;

    @Column(name = "removed_by", length = 120)
    private String removedBy;

    /** Tracks how the row first landed in the system so admins can tell apart
     *  hand-entered rows from sheet imports. Values: {@code MANUAL},
     *  {@code IMPORT}. */
    @Column(name = "source", length = 20)
    private String source;

    /** Optimistic locking — bumped by JPA on every save; concurrent updates
     *  trip {@code ObjectOptimisticLockingFailureException} → HTTP 409. */
    @Version
    @org.hibernate.annotations.ColumnDefault("0")
    @Column(name = "version", nullable = false)
    private Long version;

    @PrePersist
    void onCreate() {
        Instant now = Instant.now();
        if (createdAt == null) createdAt = now;
        if (updatedAt == null) updatedAt = now;
        if (version == null) version = 0L;
        if (source == null) source = "MANUAL";
    }

    @PreUpdate
    void onUpdate() {
        updatedAt = Instant.now();
    }
}
